name: vosk_flutter_plugin
description: Flutter plugin for Vosk speech recognition model.
version: 1.0.2
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  archive: ^3.1.8
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: org.vosk.vosk_flutter_plugin
        pluginClass: VoskFlutterPlugin

  assets:
  - example/assets/images/
